### ISSUE TITLE
Add sva tidiers

### ISSUE THREAD

**Issue by ajbass** [StoreyLab/biobroom#8]
Need to add sva tidiers

**Comment by ajbass** [comment]
Major problem: sva is not a class.

**Comment by dgrtwo** [comment]
Is it a list?

If so, I recommend you take the approach I do in broom [here with tidy.list](https://github.com/dgrtwo/broom/blob/master/R/list_tidiers.R), which then calls non-exported, non-S3 functions [tidy_svd](https://github.com/dgrtwo/broom/blob/master/R/svd_tidiers.R), [tidy_optim](https://github.com/dgrtwo/broom/blob/5fccf5571c86e4fd24e02e53b611d3ae8adcee6b/R/optim_tidiers.R), etc.

**Comment by ajbass** [comment]
Ah nice! I will use the same strategy. Thanks!
